pretext: A clear path to help you learn Operating Systems concepts
title: AUT OS
description: Amirkabir University of Technology Operating Systems course
university: Amirkabir University of Technology
course: Operating Systems course
authors: Ashkan Shakiba, Farhad Aman, Amirfazel koozegar

course_videos: 80+
course_duration: 72
course_lessons: 20
course_resources: 40+